# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e07801c6e088c4224ba9e9cae64a3ffb8986bd35c076125c6b93af3f2ac17fa6c3b35b4a815200b04dccaae716a606ed6f50f75fde2c7483940a5566023bbde

test:
  secret_key_base: 3947884cf26c00eb2bb5827599668c8731c31a05737adf9379f3018aaf362ed0e11c4a49a5e5e836919569b257436d86f04fcf4b67d3b46edab556944dec50e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
